apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventrouter
  namespace: demo-system
  labels:
    app: "eventrouter"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: "eventrouter"
  template:
    metadata:
      labels:
        app: "eventrouter"
    spec:
      serviceAccountName: eventrouter
      containers:
      - name: eventrouter
        image: kind.local/eventrouter:latest
        imagePullPolicy: Never
        args:
          - --insecure=true
          - --debug=true
          - --v=6
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1000
    